config/routes.rb
Rails.application.routes.draw do
  root 'decay_heat#index'
  get 'calculate' => 'decay_heat#calculate'
  post 'calculate' => 'decay_heat#calculate'
  # get 'download' => 'decay_heat#download'
  get 'show' => 'decay_heat#show'
end

app/models/output_hash.rb
class OutputHash < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/decay_heat_controller.rb
require 'json'

class DecayHeatController < ApplicationController
  def index
  end

  def calculate
    hash = upload_to_hash(params[:text]) || demo_data(params[:demo]) || nil
    if output = decay_heat_calculate(hash) || check_hash(params[:output_id])
      output_hash = OutputHash.find_or_create_by(answer: output.to_json)
      @output_id = output_hash.id
      @chart = LinePlot.plot_line(output, log: params[:log].present?)
      @option = { log: params[:log].present? }
    else
      render :index
    end
  end

  def download
    write_output(check_hash(params[:id]))
    send_file("#{Rails.root}/public/uploads/temp.txt")
  end

  def show
    @output = check_hash(params[:id])
    @output_id = params[:id]
  end

  private

  def upload_to_hash(params)
    ts = []
    t0 = []
    power = []
    params.read.each_line do |line|
      a, b, c = line.split("\t")
      ts << a.to_f
      t0 << b.to_f
      power << c.to_f
    end
    # ts, t0 = ts.zip(t0).sort.transpose
    { ts: ts, t0: t0 }
  rescue
    false
  end

  def demo_data(option)
    if option
      ts = Array.new(20) { |i| (i + 1) * 365 * 24 * 3600 }
      {
        ts: ts,
        t0: Array.new(ts.size) { 63 * 30 * 24 * 3600 }
      }
    else
      false
    end
  end

  def check_hash(id)
    if output_hash = OutputHash.find_by(id: id.to_i)
      JSON.parse(output_hash.answer)
    else
      false
    end
  end

  def decay_heat_calculate(hash)
    DecayHeatWithNuclear.run(hash)
  rescue
    false
  end

  # def write_output(hash)
  #   File.open(Rails.root.join('public', 'uploads', 'temp.txt'), 'wb') do |file|
  #     file.printf("ts\tANS-1979\tANS-1973\tASB9-2\tASB9-2withoutK\n")
  #     hash['ans1979']['ts'].each_index do |i|
  #       file.printf("%.1f\t%.12f\t%.12f\t%.12f\t%.12f\n",
  #                   hash['ans1979']['ts'][i],
  #                   hash['ans1979']['p_p0'][i],
  #                   hash['ans1973']['p_p0'][i],
  #                   hash['asb9_2']['p_p0'][i],
  #                   hash['asb9_2']['p_p0_without_k'][i]
  #                  )
  #     end
  #   end
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/common/_navbar.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-header">
        <a class="navbar-brand" href=<%= root_path %>>Deacy Heat</a>
    </div>
</div>

app/views/decay_heat/calculate.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="page-header">
        <div class="jumbotron">
          <%= link_to "", root_path, :class => "btn btn-fab btn-raised btn-material-red mdi-navigation-arrow-back" %>
          <% if @chart %>
          <%= high_chart("1", @chart) %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-3 col-md-offset-3">
        <div class="bs-component">
          <%= form_tag({action: :calculate}, multipart: true) do %>
          <div class="col-md-12">
          <% if @option[:log] %>
          <%= hidden_field_tag 'log', nil %>
          <%= hidden_field_tag 'output_id', @output_id %>
          <%= button_tag  'linear', type: 'submit', class: 'btn btn-primary btn-block' %>
          <% else %>
          <%= hidden_field_tag 'log', true %>
          <%= hidden_field_tag 'output_id', @output_id %>
          <%= button_tag  'log', type: 'submit', class: 'btn btn-primary btn-block' %>
          <% end %>
          </div>
          <% end %>
        </div>
      </div>
      <div class="col-md-3">
        <div class="bs-component">
          <div class="col-md-12">
            <%= link_to "Output", show_path(id: @output_id), :class => "btn btn-primary btn-block" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/decay_heat/index.html.erb
<div class="container">
  <div class="page-header" id="banner">
    <div class="row">
      <div class="col-md-12">
        <h1 class="text-center">Calculate Decay Heat</h1>
        <p class="lead text-center">Showing the Decay Heat with three method</p>
      </div>
    </div>
    <div class="row">
      <div class="col-md-4 col-md-offset-4">
        <div class="well bs-component">
          <%= form_tag({action: :calculate}, multipart: true) do %>
          <fieldset>
          <div class="form-group">
              <div class="col-md-10 col-md-offset-1">
                <%= file_field_tag 'text', accept: '.txt', class: 'form-control floating-label file' %>
              </div>
              <div class="col-md-8 col-md-offset-2">
                <%= button_tag  'Upload', type: 'submit', class: 'btn btn-primary btn-block' %>
              </div>
          </div>
          </fieldset>
          <% end %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <h2 class="text-center">Or</h2>
      </div>
    </div>
    <div class="row">
      <div class="col-md-4 col-md-offset-4">
        <div class="well bs-component">
          <%= form_tag({action: :calculate}, multipart: true) do %>
          <fieldset>
          <div class="form-group">
              <div class="col-md-8 col-md-offset-2">
                <%= hidden_field_tag 'demo', value: true %>
                <%= hidden_field_tag 'first', true %>
                <%= button_tag  'Demo', type: 'submit', class: 'btn btn-primary btn-block' %>
              </div>
          </div>
          </fieldset>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/decay_heat/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="page-header">
        <div class="jumbotron">
          <div class="row">
            <div class="col-md-2 col-md-offset-1">
              <p class="lead text-center">ts</p>
              <% @output['ans1979']['ts'].each_index do |i| %>
              <p class="lead text-center"><%= '%.0f' %@output['ans1979']['ts'][i] %></p>
              <% end %>
            </div>
            <div class="col-md-2">
              <p class="lead text-center">ANS-1979</p>
              <% @output['ans1979']['p_p0'].each_index do |i| %>
              <p class="lead text-center"><%= '%.3E' %@output['ans1979']['p_p0'][i] %></p>
              <% end %>
            </div>
            <div class="col-md-2">
              <p class="lead text-center">ANS-1973</p>
              <% @output['ans1973']['p_p0'].each_index do |i| %>
              <p class="lead text-center"><%= '%.3E' %@output['ans1973']['p_p0'][i] %></p>
              <% end %>
            </div>
            <div class="col-md-2">
              <p class="lead text-center">ASB9-2</p>
              <% @output['asb9_2']['p_p0'].each_index do |i| %>
              <p class="lead text-center"><%= '%.3E' %@output['asb9_2']['p_p0'][i] %></p>
              <% end %>
            </div>
            <div class="col-md-2">
              <p class="lead text-center">ASB9-2withoutK</p>
              <% @output['asb9_2']['p_p0_without_k'].each_index do |i| %>
              <p class="lead text-center"><%= '%.3E' %@output['asb9_2']['p_p0_without_k'][i] %></p>
              <% end %>
            </div>
          </div>
          <div class="col-md-4 col-md-offset-4 text-center">
            <%= link_to "", calculate_path(output_id: @output_id), :class => "btn btn-fab btn-raised btn-material-red mdi-navigation-arrow-back" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DecayHeat</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render :partial => "common/navbar" %>
<%= yield %>

</body>
</html>